routes/web.php
<?php

declare(strict_types=1);

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ListBlocksByWalletController;
use App\Http\Controllers\ListVotersByWalletController;
use App\Http\Controllers\ShowBlockController;
use App\Http\Controllers\ShowTransactionController;
use App\Http\Controllers\ShowWalletController;
use App\Http\Controllers\TransactionsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', HomeController::class)->name('home');
Route::view('/search', 'app.search-results')->name('search');
Route::view('/delegates', 'app.delegates')->name('delegates');

Route::view('/blocks', 'blocks')->name('blocks');
Route::get('/blocks/{block}', ShowBlockController::class)->name('block');

Route::get('/transactions', TransactionsController::class)->name('transactions');
Route::get('/transactions/{transaction}', ShowTransactionController::class)->name('transaction');

Route::view('/wallets', 'app.wallets')->name('wallets');
Route::get('/wallets/{wallet}', ShowWalletController::class)->name('wallet');
Route::get('/wallets/{wallet}/voters', ListVotersByWalletController::class)->name('wallet.voters');
Route::get('/wallets/{wallet}/blocks', ListBlocksByWalletController::class)->name('wallet.blocks');

Route::view('/statistics', 'app.statistics')->name('statistics');

// Explorer 3.0 BC - Remove after some time!
Route::redirect('/advanced-search', '/search');
Route::redirect('/block/{blockId}', '/blocks/{blockId}');
Route::redirect('/delegate-monitor', '/delegates');
Route::redirect('/top-wallets', '/wallets');
Route::redirect('/transaction/{transactionId}', '/transactions/{transactionId}');
Route::redirect('/wallet/{walletId}', '/wallets/{walletId}');

app/Http/Livewire/SearchModule.php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Contracts\Search;
use App\Http\Livewire\Concerns\ManagesSearch;
use App\Services\Forms;
use App\Services\Search\BlockSearch;
use App\Services\Search\TransactionSearch;
use App\Services\Search\WalletSearch;
use ARKEcosystem\UserInterface\Http\Livewire\Concerns\HasModal;
use Closure;
use Illuminate\Support\Arr;
use Illuminate\View\View;
use Livewire\Component;

final class SearchModule extends Component
{
    use ManagesSearch;
    use HasModal;

    public bool $isModal = false;

    public string $type = 'block';

    /** @phpstan-ignore-next-line */
    protected $queryString = [
        'state' => ['except' => []],
    ];

    /* @phpstan-ignore-next-line */
    protected $listeners = [
        'openSearchModal' => 'openModal',
    ];

    public function mount(bool $isModal = false, string $type = 'block'): void
    {
        $this->isModal    = $isModal;
        $this->type       = $type;
    }

    public function render(): View
    {
        if ($this->isModal) {
            return view('components.general.search.search-modal', [
                'transactionOptions' => Forms::getTransactionOptions(),
            ]);
        }

        return view('components.general.search.search', [
            'transactionOptions' => Forms::getTransactionOptions(),
        ]);
    }

    public function performSearch(): void
    {
        $data = $this->validateSearchQuery();

        if (array_key_exists('term', $data) && ! is_null($data['term'])) {
            $data['term'] = preg_replace('/(0x[0-9A-Z]+)/', '', $data['term']);
        }

        if ($this->searchWallet($data)) {
            return;
        }

        if ($this->searchBlock($data)) {
            return;
        }

        if ($this->searchTransaction($data)) {
            return;
        }

        $this->redirectRoute('search', ['state' => $data]);
    }

    private function searchWallet(array $data): bool
    {
        return $this->searchWithService(new WalletSearch(), $data, fn ($model) => $this->redirectRoute('wallet', $model->address));
    }

    private function searchTransaction(array $data): bool
    {
        return $this->searchWithService(new TransactionSearch(), $data, fn ($model) => $this->redirectRoute('transaction', $model->id));
    }

    private function searchBlock(array $data): bool
    {
        return $this->searchWithService(new BlockSearch(), $data, fn ($model) => $this->redirectRoute('block', $model->id));
    }

    private function searchWithService(Search $service, array $data, Closure $callback): bool
    {
        $term = Arr::get($data, 'term');

        // Skip and search for everything if the term is empty
        if (is_null($term) || $term === '') {
            return false;
        }

        // We have an advanced search so we skip looking for a specific model
        if (count($data) > 2) {
            return false;
        }

        $model = $service->search(['term' => $term])->first();

        if (is_null($model)) {
            return false;
        }

        $callback($model);

        return true;
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ trim(View::yieldContent('title', trans("metatags.home.title"))) }}</title>

        <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#c9292c">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">

        <!-- Meta --->
        <x-ark-metadata-tags>
            <x-slot name="title">@yield('meta-title', trans('metatags.home.title'))</x-slot>
            <x-slot name="description">@yield('meta-description', trans('metatags.home.description'))</x-slot>
            <x-slot name="image">@yield('meta-image', trans('metatags.home.image'))</x-slot>
        </x-ark-metadata-tags>

        <!-- Styles -->
        <link href="{{ mix('css/app.css') }}" rel="stylesheet">
        @livewireStyles

        <!-- Scripts -->
        @stack('scripts')
    </head>
    <body
        class="@if(Settings::usesDarkTheme()) dark @endif @if(Settings::usesCompactTables()) table-compact @endif"
        x-data="{ 'theme': '{{ Settings::theme() }}', 'compact': {{ Settings::usesCompactTables() ? 'true' : 'false' }} }"
        :class="{ 'dark': theme === 'dark', 'table-compact': compact }"
        @toggle-dark-mode.window="theme === 'dark' ? theme = 'light' : theme = 'dark'"
        @toggle-compact-table="compact = ! compact"
    >
        <div id="app" class="flex flex-col antialiased bg-white dark:bg-theme-secondary-900">
            <x-navbar.navbar
                :navigation="[
                    ['route' => 'delegates',  'label' => trans('menus.delegates')],
                    ['route' => 'wallets',    'label' => trans('menus.wallets')],
                    ['route' => 'statistics', 'label' => trans('menus.statistics')],
                ]"
            >
                <x-slot name="logo">
                    <x-navbar.logo />
                </x-slot>
            </x-navbar.navbar>

            <main class="container flex flex-1 w-full mx-auto @unless($isLanding ?? false) pb-14 mt-16 @endif sm:max-w-full @unless($fullWidth ?? false) px-4 sm:px-8 lg:max-w-7xl @endif">
                <div class="{{ $containerChildClass ?? 'w-full bg-white dark:bg-theme-secondary-900' }}">
                    @yield('content')
                </div>
            </main>
        </div>

        <x-ark-footer>
            <x-slot name="copyrightSlot">
                <div class="flex">
                    <span class="mx-1 sm:inline"> | </span>
                    <span class="flex items-center space-x-2 whitespace-nowrap">
                        <span>@lang('general.market_data_by')</span>

                        <a
                            href="@lang('general.urls.coingecko')"
                            target="_blank"
                        >
                            <x-ark-icon
                                name="brands.coingecko"
                                class="inline-block -mt-1"
                            />
                        </a>
                    </span>
                </div>
            </x-slot>
        </x-ark-footer>

        <livewire:search-module is-modal />

        @livewireScripts()

        @stack('scripts')

        <!-- Scripts -->
        <script src="{{ mix('js/manifest.js') }}" defer></script>
        <script src="{{ mix('js/vendor.js') }}" defer></script>
        <script src="{{ mix('js/app.js') }}" defer></script>
    </body>
</html>